modLoader = "javafml"
loaderVersion = "[1,)"
license = "GLGPL-3.0"
issueTrackerURL = "https://github.com/jackperry2187/Effigies/issues"

[[mods]]
modId = "effigies"
version = "${version}"
displayName = "Effigies"
authors = "jackperry2187"
description = '''
A Minecraft mod that adds powerful mob spawning prevention options to the game.
'''
logoFile = "assets/effigies/icon.png"

[[dependencies.effigies]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.effigies]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
