modLoader = "javafml"
loaderVersion = "[1,)"
license = "GLGPL-3.0"
issueTrackerURL = "https://github.com/jackperry2187/Effigies/issues"

[[mods]]
modId = "effigies"
version = "${version}"
displayName = "Effigies"
authors = "jackperry2187"
description = '''
A Minecraft mod that adds powerful mob spawning prevention options to the game.
'''
logoFile = "assets/effigies/icon.png"

[[mixins]]
config = "effigies.mixins.json"

[[dependencies.effigies]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.effigies]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.effigies]]
modId = "jei"
type = "optional"
versionRange = "[27,)"
ordering = "AFTER"
side = "CLIENT"
